name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  fluttertoast: ^8.2.5
  dio: ^5.4.3+1
  get: ^4.6.6
  feather_icons: ^1.2.0
  cached_network_image: ^3.3.1
  intl: ^0.18.1
  lottie: ^3.1.1
  uuid: ^4.4.0
  flutter_slidable: ^3.1.0
  get_storage: ^2.1.1
  connectivity_plus: ^6.0.3
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lotties/
    # - assets/app_ss/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

