// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU8pOPBp_xsDWoWVq6ABehAZkR9fCPKVU',
    appId: '1:492854166439:web:8d7fdce5fb1cef8704ec82',
    messagingSenderId: '492854166439',
    projectId: 'news-app-2024',
    authDomain: 'news-app-2024.firebaseapp.com',
    storageBucket: 'news-app-2024.appspot.com',
    measurementId: 'G-FVSRN7YV2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCepph0RUnyM3-PDaEgf2CNVXp1Laqq7Vg',
    appId: '1:492854166439:android:f2c74e58d2b0e62404ec82',
    messagingSenderId: '492854166439',
    projectId: 'news-app-2024',
    storageBucket: 'news-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRoZ2LMiJSOfJGGo4V-MwK8K1veEgMQU',
    appId: '1:492854166439:ios:bee40b3b5f5e6a9204ec82',
    messagingSenderId: '492854166439',
    projectId: 'news-app-2024',
    storageBucket: 'news-app-2024.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKRoZ2LMiJSOfJGGo4V-MwK8K1veEgMQU',
    appId: '1:492854166439:ios:bee40b3b5f5e6a9204ec82',
    messagingSenderId: '492854166439',
    projectId: 'news-app-2024',
    storageBucket: 'news-app-2024.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU8pOPBp_xsDWoWVq6ABehAZkR9fCPKVU',
    appId: '1:492854166439:web:4b3214e495ee944904ec82',
    messagingSenderId: '492854166439',
    projectId: 'news-app-2024',
    authDomain: 'news-app-2024.firebaseapp.com',
    storageBucket: 'news-app-2024.appspot.com',
    measurementId: 'G-R2YCMC3F49',
  );
}
